"""
Joee's Discord Testing Bot.
Now with PEP-8 Formatting!

Do not edit this file, please change the config.py.
Or, if you must, files inside the src/cogs/ folder.
However, this is not recommended unless you know what you're doing.
"""

import discord
from discord.ext import commands
from json import loads
from os import listdir

with open(
    "C:\\Users\\jcrof\\Documents\\Programming\\Python\\bot\\config.json", "r"
) as CONFIG:
    CONFIG = loads(CONFIG.read())


class MyBot(commands.Bot):
    def __init__(self):
        super().__init__(
            command_prefix=CONFIG["general_settings"]["prefix"],
            case_insensitive=True,
            description=CONFIG["cosemetic_settings"]["bot_description"],
            help_command=None,
            intents=discord.Intents.all(),
            strip_after_prefix=True,
        )

    async def setup_hook(self):
        for cogfile in listdir(
            "C:\\Users\\jcrof\\Documents\\Programming\\Python\\bot\\cogs"
        ):
            if cogfile.endswith(".py"):
                await self.load_extension(f"cogs.{cogfile[:-3]}")

        await self.tree.sync(guild=discord.Object(id=1048701639537729619))

        print(f"-> Cog Folder Synced Successfully.")

    async def on_ready(self):
        await self.wait_until_ready()
        print(
            f"-> Bot Logged In Successfully. (USERNAME = {self.user}, UID: {self.user.id})"
        )


bot = MyBot()
bot.run(CONFIG["general_settings"]["token"])
